# Generated by Django 5.2.6 on 2025-10-01 17:12

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]
    operations = [
        migrations.AddField(
            model_name='canteach',
            name='available_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
