# Generated by Django 5.2.6 on 2025-10-01 17:18

from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_canteach_available_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteach',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
